name: Issue Response Bot (Codex)

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created]

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  respond-to-issue:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install OpenAI Codex
        run: |
          npm install -g codex
        
      - name: Process issue with Codex
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CODEX_QUIET_MODE: "1"
        run: |
          # Codexを使ってissueに対応
          codex -a auto-edit "$(cat << 'EOF'
          このissueに対応してください：
          Issue番号: #${{ github.event.issue.number }}
          タイトル: ${{ github.event.issue.title }}
          内容: ${{ github.event.issue.body }}

          以下のアクションを実行してください：
          1. issueの内容を分析して、適切な返信をGitHubのissueにコメントとして投稿
          2. コードの修正が必要な場合は、新しいブランチを作成し、修正コードを適用してプルリクエストを作成
          3. ドキュメントの改善が必要な場合は、READMEを更新してプルリクエストを作成
          4. このすべての操作を自動で行う

          重要: GitHubのトークンは環境変数 GITHUB_TOKEN で利用可能です。
          EOF
          )"
      
      - name: Commit and push changes (if any)
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "Auto: Codexによるissue対応 #${{ github.event.issue.number }}"
            git push
          fi
