name: README Translation Bot

on:
  schedule:
    - cron: '0 0 * * 0'  # 毎週日曜日の0時に実行
  workflow_dispatch:  # 手動実行も可能

permissions:
  contents: write
  pull-requests: write

jobs:
  translate-readme:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install openai @octokit/rest
        
      - name: Translate README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          node .github/scripts/readme-translation.js
